Map countryJsonList = {
  'Afghanistan': 'Afghanistan Afghani',
  'Albania': 'Albanian Lek',
  'Algeria': 'Algerian Dinar',
  'American Samoa': 'US Dollar',
  'Andorra': 'Euro',
  'Angola': 'Angolan Kwanza',
  'Anguilla': 'East Caribbean Dollar',
  'Antarctica': 'East Caribbean Dollar',
  'Antigua and Barbuda': 'East Caribbean Dollar',
  'Argentina': 'Argentine Peso',
  'Armenia': 'Armenian Dram',
  'Aruba': 'Aruban Guilder',
  'Australia': 'Australian Dollar',
  'Austria': 'Euro',
  'Azerbaijan': 'Azerbaijan New Manat',
  'Bahamas': 'Bahamian Dollar',
  'Bahrain': 'Bahraini Dinar',
  'Bangladesh': 'Bangladeshi Taka',
  'Barbados': 'Barbados Dollar',
  'Belarus': 'Belarussian Ruble',
  'Belgium': 'Euro',
  'Belize': 'Belize Dollar',
  'Benin': 'CFA Franc BCEAO',
  'Bermuda': 'Bermudian Dollar',
  'Bhutan': 'Bhutan Ngultrum',
  'Bolivia': 'Boliviano',
  'Bosnia and Herzegovina': null,
  'Botswana': 'Botswana Pula',
  'Bouvet Island': 'Norwegian Krone',
  'Brazil': 'Brazilian Real',
  'British Indian Ocean Territory': 'US Dollar',
  'Brunei': null,
  'Bulgaria': 'Bulgarian Lev',
  'Burkina Faso': 'CFA Franc BCEAO',
  'Burundi': 'Burundi Franc',
  'Cambodia': 'Kampuchean Riel',
  'Cameroon': 'CFA Franc BEAC',
  'Canada': 'Canadian Dollar',
  'Cape Verde': 'Cape Verde Escudo',
  'Cayman Islands': 'Cayman Islands Dollar',
  'Central African Republic': 'CFA Franc BEAC',
  'Chad': null,
  'Chile': 'Chilean Peso',
  'China': 'Yuan Renminbi',
  'Christmas Island': 'Australian Dollar',
  'Cocos (Keeling) Islands': ' Australian Dollar',
  'Colombia': 'Colombian Peso',
  'Comoros': 'Comoros Franc',
  'Congo': 'CFA Franc BEAC',
  'Cook Islands': 'New Zealand Dollar',
  'Costa Rica': 'Costa Rican Colon',
  'Croatia': 'Croatian Kuna',
  'Cuba': 'Cuban Peso',
  'Cyprus': 'Euro',
  'Czech Republic': null,
  'Denmark': 'Danish Krone',
  'Djibouti': 'Djibouti Franc',
  'Dominica': 'East Caribbean Dollar',
  'Dominican Republic': 'Dominican Peso',
  'East Timor': null,
  'Ecuador': 'Ecuador Sucre',
  'Egypt': 'Egyptian Pound',
  'El Salvador': 'El Salvador Colon',
  'England': null,
  'Equatorial Guinea': 'CFA Franc BEAC',
  'Eritrea': 'Eritrean Nakfa',
  'Estonia': 'Euro',
  'Ethiopia': 'Ethiopian Birr',
  'Falkland Islands': null,
  'Faroe Islands': ' Danish Krone',
  'Fiji Islands': null,
  'Finland': 'Euro',
  'France': 'Euro',
  'French Guiana': 'Euro',
  'French Polynesia': null,
  'French Southern territories': 'Euro',
  'Gabon': 'CFA Franc BEAC',
  'Gambia': 'Gambian Dalasi',
  'Georgia': 'Georgian Lari',
  'Germany': 'Euro',
  'Ghana': 'Ghanaian Cedi',
  'Gibraltar': 'Gibraltar Pound',
  'Greece': 'Euro',
  'Greenland': 'Danish Krone',
  'Grenada': 'East Carribean Dollar',
  'Guadeloupe': null,
  'Guam': null,
  'Guatemala': 'Guatemalan Quetzal',
  'Guinea': 'Guinea Franc',
  'Guinea-Bissau': null,
  'Guyana': 'Guyana Dollar',
  'Haiti': 'Haitian Gourde',
  'Heard Island and McDonald Islands': 'Australian Dollar',
  'Holy See (Vatican City State)': null,
  'Honduras': 'Honduran Lempira',
  'Hong Kong': 'Hong Kong Dollar',
  'Hungary': 'Hungarian Forint',
  'Iceland': 'Iceland Krona',
  'India': 'Indian Rupee',
  'Indonesia': 'Indonesian Rupiah',
  'Iran': 'Iranian Rial',
  'Iraq': 'Iraqi Dinar',
  'Ireland': 'Euro',
  'Israel': 'Israeli New Shekel',
  'Italy': 'Euro',
  'Ivory Coast': 'CFA Franc BCEAO',
  'Jamaica': 'Jamaican Dollar',
  'Japan': 'Japanese Yen',
  'Jordan': 'Jordanian Dinar',
  'Kazakhstan': null,
  'Kenya': 'Kenyan Shilling',
  'Kiribati': 'Australian Dollar',
  'Kuwait': 'Kuwaiti Dinar',
  'Kyrgyzstan': 'Som',
  'Laos': 'Lao Kip',
  'Latvia': 'Latvian Lats',
  'Lebanon': 'Lebanese Pound',
  'Lesotho': 'Lesotho Loti',
  'Liberia': 'Liberian Dollar',
  'Libyan Arab Jamahiriya': null,
  'Liechtenstein': 'Swiss Franc',
  'Lithuania': 'Lithuanian Litas',
  'Luxembourg': 'Euro',
  'Macao': null,
  'North Macedonia': 'Denar',
  'Madagascar': 'Malagasy Franc',
  'Malawi': 'Malawi Kwacha',
  'Malaysia': 'Malaysian Ringgit',
  'Maldives': 'Maldive Rufiyaa',
  'Mali': 'CFA Franc BCEAO',
  'Malta': 'Euro',
  'Marshall Islands': 'US Dollar',
  'Martinique': null,
  'Mauritania': 'Mauritanian Ouguiya',
  'Mauritius': 'Mauritius Rupee',
  'Mayotte': 'Euro',
  'Mexico': 'Mexican Nuevo Peso',
  'Micronesia, Federated States of': null,
  'Moldova': 'Moldovan Leu',
  'Monaco': null,
  'Mongolia': 'Mongolian Tugrik',
  'Montserrat': 'East Caribbean Dollar',
  'Morocco': 'Moroccan Dirham',
  'Mozambique': 'Mozambique Metical',
  'Myanmar': 'Myanmar Kyat',
  'Namibia': 'Namibian Dollar',
  'Nauru': 'Australian Dollar',
  'Nepal': 'Nepalese Rupee',
  'Netherlands': 'Euro',
  'Netherlands Antilles': 'Netherlands Antillean Guilder',
  'New Caledonia': null,
  'New Zealand': 'New Zealand Dollar',
  'Nicaragua': 'Nicaraguan Cordoba Oro',
  'Niger': 'CFA Franc BCEAO',
  'Nigeria': 'Nigerian Naira',
  'Niue': 'New Zealand Dollar',
  'Norfolk Island': 'Australian Dollar',
  'North Korea': 'North Korean Won',
  'Northern Ireland': null,
  'Northern Mariana Islands': 'US Dollar',
  'Norway': 'Norwegian Krone',
  'Oman': 'Omani Rial',
  'Pakistan': 'Pakistan Rupee',
  'Palau': 'US Dollar',
  'Palestine': null,
  'Panama': 'Panamanian Balboa',
  'Papua New Guinea': 'Papua New Guinea Kina',
  'Paraguay': 'Paraguay Guarani',
  'Peru': 'Peruvian Nuevo Sol',
  'Philippines': 'Philippine Peso',
  'Pitcairn': null,
  'Poland': 'Polish Zloty',
  'Portugal': 'Euro',
  'Puerto Rico': 'US Dollar',
  'Qatar': 'Qatari Rial',
  'Reunion': null,
  'Romania': 'Romanian New Leu',
  'Russian Federation': null,
  'Rwanda': 'Rwanda Franc',
  'Saint Helena': 'St. Helena Pound',
  'Saint Kitts and Nevis': null,
  'Saint Lucia': 'East Caribbean Dollar',
  'Saint Pierre and Miquelon': ' Euro',
  'Saint Vincent and the Grenadines': 'East Caribbean Dollar',
  'Samoa': 'Samoan Tala',
  'San Marino': 'Euro',
  'Sao Tome and Principe': ' Dobra',
  'Saudi Arabia': 'Saudi Riyal',
  'Scotland': null,
  'Senegal': 'CFA Franc BCEAO',
  'Serbia': 'Serbian dinar',
  'Seychelles': 'Seychelles Rupee',
  'Sierra Leone': 'Sierra Leone Leone',
  'Singapore': 'Singapore Dollar',
  'Slovakia': 'Euro',
  'Slovenia': 'Euro',
  'Solomon Islands': 'Solomon Islands Dollar',
  'Somalia': 'Somali Shilling',
  'South Africa': 'South African Rand',
  'South Georgia and the South Sandwich Islands': 'Pound Sterling',
  'South Korea': 'Korean Won',
  'South Sudan': 'South Sudan Pound',
  'Spain': 'Euro',
  'SriLanka': null,
  'Sudan': 'Sudanese Pound',
  'Suriname': 'Surinam Dollar',
  'Svalbard and Jan Mayen': null,
  'Swaziland': 'Swaziland Lilangeni',
  'Sweden': 'Swedish Krona',
  'Switzerland': 'Swiss Franc',
  'Syria': 'Syrian Pound',
  'Tajikistan': 'Tajik Somoni',
  'Tanzania': 'Tanzanian Shilling',
  'Thailand': 'Thai Baht',
  'The Democratic Republic of Congo': 'Franc Congolais',
  'Togo': 'CFA Franc BCEAO',
  'Tokelau': 'New Zealand Dollar',
  'Tonga': 'Tongan Pa\'anga',
  'Trinidad and Tobago': 'Trinidad and Tobago Dollar',
  'Tunisia': 'Tunisian Dollar',
  'Turkey': 'Turkish Lira',
  'Turkmenistan': 'Manat',
  'Turks and Caicos Islands': null,
  'Tuvalu': 'Australian Dollar',
  'Uganda': 'Uganda Shilling',
  'Ukraine': 'Ukraine Hryvnia',
  'United Arab Emirates': 'Arab Emirates Dirham',
  'United Kingdom': null,
  'United States': null,
  'United States Minor Outlying Islands': null,
  'Uruguay': 'Uruguayan Peso',
  'Uzbekistan': 'Uzbekistan Sum',
  'Vanuatu': 'Vanuatu Vatu',
  'Venezuela': 'Venezuelan Bolivar',
  'Vietnam': 'Vietnamese Dong',
  'Virgin Islands, British': null,
  'Virgin Islands, U.S.': null,
  'Wales': null,
  'Wallis and Futuna': null,
  'Western Sahara': 'Moroccan Dirham',
  'Yemen': 'Yemeni Rial',
  'Zambia': 'Zambian Kwacha',
  'Zimbabwe': 'Zimbabwe Dollar'
};
